name: Supabase Continuous Deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRODUCTION_PROJECT_ID: ${{secrets.PROJECT_REF}}
      SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_ROLE_KEY}}
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      ENGINE: ${{secrets.ENGINE}}
      PORT: ${{secrets.PORT}}
      ROOT_FOLDER: ${{secrets.ROOT_FOLDER}}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: |
          supabase link --project-ref $PRODUCTION_PROJECT_ID
          supabase functions deploy collage
          supabase secrets set SUPABASE_URL=$SUPABASE_URL
          supabase secrets set SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
          supabase secrets set PORT=$PORT
          supabase secrets set ENGINE=$ENGINE
          supabase secrets set ROOT_FOLDER=$ROOT_FOLDER
